title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Finn Carpenter
github_username: F1nnC
baseurl: "/stud"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/primer@v0.6.0
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache
future: true
