title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: "/stud"
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/primer@v0.6.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache
future: true
